name: publish-snapshot
on:
  workflow_dispatch:
  push:
    branches: [dev]
jobs:
  publish-to-maven:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning Repo
        uses: actions/checkout@v3
      - name: Setting up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Grant permissions to Gradle
        run: chmod +x gradlew
      - name: Publish with Gradle
        run: ./gradlew clean publish :client-api:publish -Pcreds.maven.user='${{ secrets.MAVEN_REPO_USER }}' -Pcreds.maven.key='${{ secrets.MAVEN_REPO_PASS }}' -PisSnapshot=true -Dorg.gradle.jvmargs=-Xmx512m -Pdm.gpr.user=${{ secrets.DM_GPR_USER }} -Pdm.gpr.key=${{ secrets.DM_GPR_KEY }}